package analisadorlexico;

public enum Token {
    LINHA, PALAVRA_RESERVADA, IDENTIFICADOR, NUMERO_INTEIRO, NUMERO_REAL, DELIMITADORES,
    ATRIBUICAO, RELACIONAL, ADITIVO, MULTIPLICATIVO, ERROR,
}
